[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "pyfiglet>=1.0.2",
    "requests>=2.32.3",
    "rich>=14.0.0",
]
